# Generated by Django 3.0.6 on 2020-08-16 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='role',
            field=models.CharField(default='hi', max_length=25),
            preserve_default=False,
        ),
    ]
