# Generated by Django 3.0.6 on 2020-08-24 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200822_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default_profile.png', upload_to='profile_pics_bugtrack'),
        ),
    ]
