# Generated by Django 3.0.6 on 2020-08-21 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_membership_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='pin',
            field=models.IntegerField(),
        ),
    ]
