# Generated by Django 3.0.6 on 2020-08-26 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200824_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('DEVELOPER', 'Developer'), ('PROJECT_MANAGER', 'Project Manager'), ('CLIENT', 'Client')], default='None', max_length=128),
        ),
    ]
