# Generated by Django 3.0.6 on 2020-08-26 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200826_0508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Developer', 'Developer'), ('Project Manager', 'Project Manager'), ('Client', 'Client')], default='None', max_length=128),
        ),
    ]
