# Generated by Django 3.0.6 on 2020-08-28 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200826_0509'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='description',
            field=models.CharField(default='description', max_length=500),
            preserve_default=False,
        ),
    ]
