# Generated by Django 3.0.6 on 2020-08-09 00:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectMembers',
            new_name='ProjectMember',
        ),
    ]
