# Generated by Django 3.0.6 on 2020-08-21 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='ticket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.Ticket'),
        ),
    ]
