# Generated by Django 3.0.6 on 2020-08-25 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0007_auto_20200824_1838'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketDev',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.Ticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='developers',
            field=models.ManyToManyField(related_name='ticket_developers', through='tickets.TicketDev', to=settings.AUTH_USER_MODEL),
        ),
    ]
