# Generated by Django 3.0.6 on 2020-08-25 16:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_auto_20200825_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketdev',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
