# Generated by Django 3.0.6 on 2020-08-28 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_ticketdev_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='icon_type',
            field=models.CharField(default='def', max_length=200),
            preserve_default=False,
        ),
    ]
