# Generated by Django 3.0.6 on 2020-09-01 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_history_icon_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='subject',
            field=models.CharField(default='default subject', max_length=128),
            preserve_default=False,
        ),
    ]
