# Generated by Django 3.0.6 on 2020-09-02 18:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0012_auto_20200902_0555'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='deadline',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
