# Generated by Django 3.0.6 on 2020-09-07 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0016_auto_20200902_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(choices=[('Bug', 'Bug'), ('New Feature', 'New Feature'), ('Improvement', 'Improvement'), ('Task', 'Task')], default='Task', max_length=128),
        ),
    ]
